### ISSUE TITLE
Color picker should close when user clicks anywhere in page outside color picker

### ISSUE THREAD

**Issue by webextensions** [easylogic/codemirror-colorpicker#9]
Currently, the color picker closes when the user clicks or scrolls inside the CodeMirror.

**The color picker should also close when user clicks anywhere in page outside color picker (and outside codemirror).**

**How does CodeMirror detect clicks outside its instance:**
From what I see, CodeMirror does it by using an invisible textarea element. Whenever the user clicks anywhere in the CodeMirror, that textarea element gets the focus. When the user clicks anywhere outside, the textarea element loses focus and CodeMirror fires its 'blur' event. We can check it by logging document.activeElement. I believe the reason for this would be that browsers work well for .focus() and .blur() with input/textarea elements.

The code to detect outside clicks may not simply rely on detecting click on the page body, because some component may stop bubbling of click event. Using .blur() of an input/textarea element guarantees the detection of focus change even in those cases.

**Comment by easylogic** [comment]
@webextensions 


I knew about the problem you gave me. However, I did not do it because it was not clear what to do in CodeMirror or what to do in external body.

For example, you may wonder if an extension defined within CodeMirror can trigger an event on a document.

This is because the event handler can be set and can not be released if it is designed incorrectly.

Or you could write code that erases all of the events set in the body from the outside, so no event goes out of the CodeMirror.

I'll try to think more about this problem.

**Comment by webextensions** [comment]
Yes, it is not a simple thing to solve.

For my use case, I went for an alternative timer based approach along with detecting mouseenter and mouseleave events. My approach is not an ideal one, but is an ok enough workaround for my custom requirement.

**Let me attach the code I modified for my PoC. Currently, the code below uses jQuery for event handling.** If you find it worthy, you might consider making it a configuration option (where user can pass a delay in milliseconds) :-)

```
var timerCloseColorPicker;
codemirror_colorpicker.prototype.open_color_picker = function (el) {
    var lineNo = el.lineNo;
    var ch = el.ch;
    var nameColor = el.nameColor;
    var color = el.color;

    if (this.colorpicker) {
        var self = this;
        var prevColor = color;
        var pos = this.cm.charCoords({line : lineNo, ch : ch });
        this.colorpicker.show({ left : pos.left, top : pos.bottom, isShortCut : el.isShortCut || false }, nameColor || color, function (newColor) {
            self.cm.replaceRange(newColor, { line : lineNo, ch : ch } , { line : lineNo, ch : ch + prevColor.length }, '*colorpicker');
            prevColor = newColor;
        });

        var that = this;
        var hideColorPickerIfRequired = function () {
            if (that.cm.state.colorpicker.is_edit_mode()) {
                that.close_color_picker();
            }
        };

        jQuery(that.colorpicker.$root.el).off('mouseenter').on('mouseenter', function () {
            clearTimeout(timerCloseColorPicker);
        }).off('mouseleave').on('mouseleave', function () {
            clearTimeout(timerCloseColorPicker);
            timerCloseColorPicker = setTimeout(hideColorPickerIfRequired, 2000);
        });
        clearTimeout(timerCloseColorPicker);
        timerCloseColorPicker = setTimeout(hideColorPickerIfRequired, 2000);
    }
}
```

**Comment by easylogic** [comment]
@webextensions 

Thank you for your ideas.
I will design the function well.

**Comment by teleclimber** [comment]
I ran into this as well.

It's useful to look at how `show-hints` does things to get guidance on best possible solution.

In `show-hint` they close the hint by listening for blur: `cm.on( 'blur', close... )`

This doesn't work here because clicking on the colorpicker blurs codemirror. Sometimes you can prevent clicks from blurring inputs but it's not possible here because user must be able to input values directly inside the colorpicker using `input` elements there.

I suggest the following:

1. When user opens colorpicker focus the first input element inside colorpicker (like `R` input in RGB mode)
2. Whenever a user clicks on anywhere on the colorpicker check if any of colorpicker's input elements are the active element. If not, focus the first input element in colorpicker.
3. listen for cm's blur event. On blur check to see if any of the internal `input` elements are the active element. If none of the internal input elements are active then close color picker.
4. listen for blur events on internal input elements. If no internal elements are active, close dialog.

Note that for 3 and 4 there may need to be a timeout set before you actually check the active element.

As for 2., which is a bit hacky, consider making both sliders and the big gradient focusable inputs. This would be better for keyboard users, and you wouldn't have to force the focus on the bottom inputs.

As a general note, I think that sticking with blur events is more "correct" because some users may want to use the keyboard only to edit colors (which doesn't really work right now, but that's for another issue.

Thanks!

**Comment by easylogic** [comment]
i add hideDelay option to master branch. 

default value is  2,000 ms. 

```javascript
colorpicker : {
    mode : 'edit', 
    hideDelay : 3000 // (default  2000 ms) 
}
```

When you click outside codemirror,  color picker will hide after hideDelay time

**Comment by webextensions** [comment]
Thanks a lot :-)
